apiVersion: batch/v1
kind: Job
metadata:
  name: exp01-example-cpu
spec:
  template:
    spec:
      containers:
      - name: ml
        image: hongkunyoo/eks-ml:example
        imagePullPolicy: Always
        command: ["python", "train.py"]
        args: ['5', 'softmax', '0.5']
        resources:
          limits:
            cpu: "1"
            memory: "5Gi"
      restartPolicy: Never
  backoffLimit: 0

